//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationId { get; set; }
        public int LibId { get; set; }
        public string AspNetUserId { get; set; }
        public Nullable<System.DateTime> DateOfApplication { get; set; }
        public Nullable<System.DateTime> DateOfVerification { get; set; }
        public string AspNetLibrarianId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Library Library { get; set; }
    }
}
