//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interact
    {
        public int InterID { get; set; }
        public int BookID { get; set; }
        public string AspNetUsersID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Book Book { get; set; }
    }
}
