//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibrarianApplication
    {
        public int LibrarianAppId { get; set; }
        public string AspNetLibrarianId { get; set; }
        public string AspNetSuperUser { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public Nullable<System.DateTime> DateAccepted { get; set; }
        public int LibId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Library Library { get; set; }
    }
}
