//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Petition
    {
        public int PetID { get; set; }
        public int LibID { get; set; }
        public string AspNetUsersId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Library Library { get; set; }
    }
}
